export const MobileNavLinks = () => {
  return (
    <nav
      role="navigation"
      alt=""
      className="items-stretch box-border caret-transparent flex justify-start leading-6 max-w-full min-w-36 outline-[3px] break-words relative text-start no-underline w-full mt-[113px] left-0 top-0"
    >
      <ul
        role="menubar"
        className="box-border caret-transparent flex basis-full flex-col grow justify-start list-inside list-none min-h-[auto] min-w-[auto] outline-[3px] break-words no-underline align-top pl-0 md:min-h-0 md:min-w-0"
      >
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-[21px] before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-sm after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-[21px] after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/"
            className="items-center box-border caret-transparent text-zinc-800 flex justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:opacity-0 before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-normal after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:opacity-0 after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              HOME
              <span className="box-border caret-transparent hidden leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-[21px] before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-sm after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-[21px] after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/about"
            className="items-center box-border caret-transparent text-zinc-800 flex justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:opacity-0 before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-normal after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:opacity-0 after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              ABOUT
              <span className="box-border caret-transparent hidden leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-[21px] before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-sm after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-[21px] after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/events"
            className="items-center box-border caret-transparent text-zinc-800 flex justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:opacity-0 before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-normal after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:opacity-0 after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              EVENTS
              <span className="box-border caret-transparent hidden leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-[21px] before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-sm after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-[21px] after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/scholarships"
            className="items-center box-border caret-transparent text-zinc-800 flex font-bold justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-bold before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              SCHOLARSHIPS
              <span className="box-border caret-transparent hidden font-normal leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-[21px] before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-sm after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-[21px] after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/education"
            className="items-center box-border caret-transparent text-zinc-800 flex justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:opacity-0 before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-normal after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:opacity-0 after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              EDUCATION
              <span className="box-border caret-transparent hidden leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-[21px] before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-sm after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-[21px] after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/contact"
            className="items-center box-border caret-transparent text-zinc-800 flex justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:opacity-0 before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-normal after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:opacity-0 after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              CONTACT
              <span className="box-border caret-transparent hidden leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
        <li
          role="menuitem"
          className="box-border caret-transparent flex flex-col font-normal justify-start min-h-[auto] min-w-[auto] outline-[3px] break-words relative no-underline align-top md:min-h-0 md:min-w-0 before:accent-auto before:self-center before:box-border before:caret-transparent before:text-black before:block before:text-base before:not-italic before:normal-nums before:font-bold before:tracking-[normal] before:leading-6 before:list-inside before:list-none before:min-h-[auto] before:min-w-[auto] before:outline-[3px] before:break-words before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-arial before:md:min-h-0 before:md:min-w-0 after:accent-auto after:self-start after:box-border after:caret-transparent after:text-neutral-300 after:block after:text-base after:not-italic after:normal-nums after:font-bold after:h-0 after:tracking-[normal] after:leading-6 after:list-inside after:list-none after:min-h-[auto] after:min-w-[auto] after:outline-[3px] after:break-words after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-arial after:md:min-h-0 after:md:min-w-0"
        >
          <a
            href="/photos"
            className="items-center box-border caret-transparent text-zinc-800 flex justify-start tracking-[0.48px] min-h-[auto] min-w-[auto] break-words relative text-left no-underline align-top py-2 font-source_sans_pro md:min-h-0 md:min-w-0"
          >
            <span className="box-border caret-transparent block min-h-[auto] min-w-[auto] outline-[3px] break-words pointer-events-none no-underline md:min-h-0 md:min-w-0 before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:block before:text-base before:not-italic before:normal-nums before:font-normal before:h-0 before:tracking-[0.48px] before:leading-6 before:list-inside before:list-none before:opacity-0 before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:w-full before:border-separate before:font-source_sans_pro after:accent-auto after:box-border after:caret-transparent after:text-zinc-800 after:block after:text-base after:not-italic after:normal-nums after:font-normal after:h-0 after:tracking-[0.48px] after:leading-6 after:list-inside after:list-none after:opacity-0 after:outline-[3px] after:break-words after:pointer-events-none after:text-left after:no-underline after:indent-[0px] after:normal-case after:visible after:w-full after:border-separate after:font-source_sans_pro">
              PHOTOS
              <span className="box-border caret-transparent hidden leading-[normal] outline-[3px] break-words no-underline font-fontawesome before:accent-auto before:box-border before:caret-transparent before:text-zinc-800 before:inline-block before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[0.48px] before:leading-[normal] before:list-inside before:list-none before:outline-[3px] before:break-words before:pointer-events-none before:text-left before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-fontawesome"></span>
            </span>
          </a>
        </li>
      </ul>
    </nav>
  );
};
